### PR TITLE
fix: added sharedLayout

### LINKED ISSUE #162: [BUG] navbar re-renders on every page
### Description

Re-rendering navbar makes the state lose and animation also doesn't work properly on route change. 
Create a layout that would prevent this issue. 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Yazdun**
### Fixes Issue

Closes #162

### Changes proposed

added a sharedLayout to the project

### CODE REVIEW

**Comment by leewan-09** [comment]
I'm still able to see some glitch effects. 

https://user-images.githubusercontent.com/60838584/191109196-2f7f207f-294b-49bb-bd23-3a6826d1c1d4.mov

**Comment by leewan-09** [comment]
> I'm still able to see some glitch effects.
> 
>  Screen.Recording.2022-09-20.at.01.18.39.mov

I believe that this issue is related to frame motion

**Comment by Yazdun** [comment]
> > I'm still able to see some glitch effects.
> > Screen.Recording.2022-09-20.at.01.18.39.mov
> 
> I believe that this issue is related to frame motion

thanks for noticing the issue. the problem was with theme toggler. theme toggler mounts after page is completely painted and it changes the topbar height, so topbar is rendered with shorter height initially and then when theme toggler gets mounted, the topbar height will change and it looks glitchy. I fixed it with giving a static height to the topbar.

**Comment by leewan-09** [comment]
> > > I'm still able to see some glitch effects.
> > > Screen.Recording.2022-09-20.at.01.18.39.mov
> > 
> > 
> > I believe that this issue is related to frame motion
> 
> thanks for noticing the issue. the problem was with theme toggler. theme toggler mounts after page is completely painted and it changes the topbar height, so topbar is rendered with shorter height initially and then when theme toggler gets mounted, the topbar height will change and it looks glitchy. I fixed it with giving a static height to the topbar.

Now it looks great!

**Review by leewan-09 — APPROVED** [review]
LGTM 👍

**Review by rohitdasu — APPROVED** [review]
LGTM 👍

**Pull request merged**
