### PR TITLE
Changed tailwind absolute values

### PR DESCRIPTION
**Pull request by GMBermeo**
### Fixes Issue

Removed absolute values of classes.

### Changes proposed

This helps to tailwind export fewer classes.

### CODE REVIEW

**Comment by rohitdasu** [comment]
Hi @GMBermeo thanks for the PR. have you covered every files for fixing the tailwind absolute values?

**Comment by GMBermeo** [comment]
> Hi @GMBermeo thanks for the PR. have you covered every files for fixing the tailwind absolute values?

Hi Rohitdasu, I have covered the ones I was able to find and substitute for 1:1 values. There are ones in pixels that I've decided not to change, and others in "broken" rem values.

**Comment by rohitdasu** [comment]
> > Hi @GMBermeo thanks for the PR. have you covered every files for fixing the tailwind absolute values?
> 
> Hi Rohitdasu, I have covered the ones I was able to find and substitute for 1:1 values. There are ones in pixels that I've decided not to change, and others in "broken" rem values.

ok cool

**Review by JakubChorzepa — APPROVED** [review]
LGTM

**Pull request merged**
