### PR TITLE
fix social media links

### LINKED ISSUE #184: [FEATURE] replace textual navs to icons
### Description

replace `discord` and `github` textual navigation to only icons and put it beside the theme toggle. 
 use icons from `react-icons` package. icons should be `FaDiscord` and `FaGithub`

Screenshot 2022-09-27 at 7 53 02 PM

### PR DESCRIPTION
**Pull request by LucioHenrique512**
### Fixes Issue #184

Closes #184 

### Changes proposed

Creating a new social media link rendering component

### Screenshots
Captura de Tela 2022-09-28 às 18 49 32
Captura de Tela 2022-09-28 às 18 49 59
Captura de Tela 2022-09-28 às 18 50 09

### CODE REVIEW

**Comment by leewan-09** [comment]
@LucioHenrique512 why does the build fail? could you build it locally

**Comment by LucioHenrique512** [comment]
@leewan-09 , Of course, there was a issue with lint, but now it has been fixed,
sorry for delay.

**Comment by rohitdasu** [comment]
please use outined version of icon for mobile only so that it will match other icons 

Screenshot 2022-09-30 at 10 38 25 AM

**Review by leewan-09 — COMMENTED** [review]
It would be nice if we have even spaces 

image

**Comment by RakeshSangem** [comment]
> It would be nice if we have even spaces
> image

It would look nice when we place the theme icon at first, imo.

**Review by leewan-09 — APPROVED** [review]
LGTM

**Review by rohitdasu — APPROVED** [review]
LGTM 👍

**Pull request merged**
