### PR TITLE
feat: Added like feature frontend

### LINKED ISSUE #305: [FEATURE] Add a Like or Upvote button for each project
### Description

It would be nice having a Like or upvote button for project, so user's of the site would be able like the project, also it will put a soft impact on visitors of the project.

### PR DESCRIPTION
**Pull request by zvolcsey**
Summary of the like functionality (frontend)

Should close #305 

- `feat: Added like feature frontend` commit
  - Added like button and likesCount span element to the Project.tsx file.
  - Update the ProjectSkeleton.tsx file.
  - Update `Project.interface.ts` file.
  - Update `ProjectList.tsx` file.

- `Added liked and likesCount property to the IProject interface` commit

projectmate

### CODE REVIEW

**Comment by rohitdasu** [comment]
hi @zvolcsey could you fix the conflicts and resolve the build issue
Screenshot 2023-01-11 at 12 17 14 AM

**Comment by rupali-codes** [comment]
@zvolcsey could you please resolve conflicts? 
also, 
image

it's not showing any counts in here, can we just hide this when count is 0, rather then showing 0 it would be nice if we doesn't show it.

**Comment by zvolcsey** [comment]
Sorry, the issue is closed now. But I'm working on it and will push my fixed version soon.

**Comment by rohitdasu** [comment]
@zvolcsey if possible please make the frontend and backend changes in the same PR so we can test it well.

**Comment by zvolcsey** [comment]
@rohitdasu Okay. I will open a new PR with frontend and backend.

I created a new frontend design. If it is good, I'll add this to the new PR. Maybe the like button next to the contribution button is better. So the long titles will also look good.

projectmate-2

**Comment by rohitdasu** [comment]
> @rohitdasu Okay. I will open a new PR with frontend and backend.
> 
> I created a new frontend design. If it is good, I'll add this to the new PR. Maybe the like button next to the contribution button is better. So the long titles will also look good.
> 
> projectmate-2

looking great! one suggestion, could you please show the likes count inside the like button itself. we have room for the number. no need to show the count above the button. if 0 likes, then don't show it.

**Pull request closed without merging**
