### PR TITLE
Changed framerate speed from Hero animation to 23.976

### PR DESCRIPTION
**Pull request by GMBermeo**
Changed framerate speed from Hero animation to 23.976 to feel more fluid and less rushed.

### Fixes Issue

The Hero animation feels rushed.

### Changes proposed

Changed framerate from 29 to 23.9, now the animation feels more natural.
(Helps my anxiety)

### CODE REVIEW

**Review by JakubChorzepa — CHANGES_REQUESTED** [review]
Hey, I'd make it maybe even a little bit slower, something around 19-20 fr could be good. Have a look and give feedback how it looks.

**Comment by JakubChorzepa** [comment]
Closing due to inactivity

**Comment by GMBermeo** [comment]
Hey, sorry I was out for the weekend.
So, since the animation is automated motion, it can be slower without feeling choppy, I've tried with 15, 17 and 19, and @19fps it feels really good, I liked the way 17fps feels too.

**Comment by JakubChorzepa** [comment]
> Hey, sorry I was out for the weekend. So, since the animation is automated motion, it can be slower without feeling choppy, I've tried with 15, 17 and 19, and @19fps it feels really good, I liked the way 17fps feels too.

I'm sorry then 😄,  commit best looking fr and we'll have a look

**Review by JakubChorzepa — APPROVED** [review]

**Review by rohitdasu — APPROVED** [review]

**Pull request merged**
