### PR TITLE
Upgrade next from 12 to 13 #266

### PR DESCRIPTION
**Pull request by Xoviec**
Used ,,npm i next@latest react@latest react-dom@latest eslint-config-next@latest" & ,,npx @next/codemod new-link" and works well.

### CODE REVIEW

**Comment by rohitdasu** [comment]
could you check why build is failing?

**Comment by Xoviec** [comment]
> could you check why build is failing?
I have a problem with Vercel account so Im not able to tell you now 🤷

**Comment by rohitdasu** [comment]
> > I have a problem with Vercel account so Im not able to tell you now 🤷

you don't have access to vercel account so you can't see the logs, please try building the app locally. I strongly believe you can see the errors there. thanks

**Comment by Xoviec** [comment]
adriangasiorek@MacBook-Pro-Adrian projectmate % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: next-auth@4.15.0
npm ERR! Found: next@13.0.3
npm ERR! node_modules/next
npm ERR!   next@"^13.0.3" from the root project
npm ERR!   peer next@"*" from next-themes@0.2.1
npm ERR!   node_modules/next-themes
npm ERR!     next-themes@"^0.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12.2.5" from next-auth@4.15.0
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"^4.15.0" from the root project
npm ERR!   peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.5
npm ERR!   node_modules/@next-auth/prisma-adapter
npm ERR!     @next-auth/prisma-adapter@"^1.0.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: next@12.3.3
npm ERR! node_modules/next
npm ERR!   peer next@"^12.2.5" from next-auth@4.15.0
npm ERR!   node_modules/next-auth
npm ERR!     next-auth@"^4.15.0" from the root project
npm ERR!     peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.5
npm ERR!     node_modules/@next-auth/prisma-adapter
npm ERR!       @next-auth/prisma-adapter@"^1.0.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/adriangasiorek/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adriangasiorek/.npm/_logs/2022-11-13T12_14_41_280Z-debug-0.log
adriangasiorek@MacBook-Pro-Adrian projectmate % 

But it works after npm install --force

**Comment by rohitdasu** [comment]
@Xoviec yeah we are aware of that issue. will fix it later. as of now `--force` is good to go.

**Pull request closed without merging**
