### PR TITLE
Add project form

### LINKED ISSUE #94: [FEATURE] add project form
### Description

The `add project` form should open when user clicks on the `add project` button which is present in the fab action button.

### PR DESCRIPTION
**Pull request by AdityaPainuli**
Added project-form '/add-project' route to the application 

closes #94 

image

### CODE REVIEW

**Comment by rohitdasu** [comment]
for the light mode please make the button text color white

Screenshot 2022-09-24 at 11 29 40 AM

**Comment by rohitdasu** [comment]
description field has different padding size than other input fields. please fix it.

Screenshot 2022-09-24 at 11 29 26 AM

**Comment by RakeshSangem** [comment]
Could you please add a remove option for the upload functionality so that the user can change if they choose the incorrect image?

**Comment by AdityaPainuli** [comment]
> 

If you click on the image it will be get unselected.

**Comment by RakeshSangem** [comment]
> > 
> 
> If you click on the image it will be get unselected.

But, It would be great if we place an `close icon`. what do you think @rohitdasu

**Comment by AdityaPainuli** [comment]
> > > 
> > 
> > 
> > If you click on the image it will be get unselected.
> 
> But, It would be great if we place an `close icon`. what do you think @rohitdasu

Yes but it would great but we don't know the dimension user image is going to be so our icon will be sometimes inside the image and sometimes outside of it at the corner.

**Comment by rohitdasu** [comment]
> > > > 
> > > 
> > > 
> > > If you click on the image it will be get unselected.
> > 
> > 
> > But, It would be great if we place an `close icon`. what do you think @rohitdasu
> 
> Yes but it would great but we don't know the dimension user image is going to be so our icon will be sometimes inside the image and sometimes outside of it at the corner.

that's fine, adding indicator is good. we should definitely add a close icon to this otherwise user will get confused.

**Comment by RakeshSangem** [comment]
Even it took sometime for me to remote at first😁. So having a indication icon is good practice.

**Comment by rohitdasu** [comment]
close functionality works fine 👍 

i've 2 more changes: 
1. please add some margin at the bottom, submit button is very close to the bottom
2. integrate the add-project page with the floating action button

Screenshot 2022-09-24 at 11 50 04 AM

**Pull request merged**
