### PR TITLE
Feature/next auth

### PR DESCRIPTION
**Pull request by leewan-09**
### Changes proposed

- Change to next auth
- Removed create user API 
- Store user information in DB

### Note to reviewers

- To completely remove firebase we have to remove the old navbar component
- And Prisma seeder is broken for now

### CODE REVIEW

**Comment by RakeshSangem** [comment]
### Hey @leewan-09 , Why it's asking for username and password when click on continue with google?

Screenshot 2022-09-21 143749

**Comment by rohitdasu** [comment]
> ### Hey @leewan-09 , Why it's asking for username and password when click on continue with google?
> Screenshot 2022-09-21 143749

this will show in preview link and dev environment. for production it will show the actual provider auth

**Comment by RakeshSangem** [comment]
> > ### Hey @leewan-09 , Why it's asking for username and password when click on continue with google?
> > Screenshot 2022-09-21 143749
> 
> this will show in preview link and dev environment. for production it will show the actual provider auth

So can we merge this PR?

**Comment by leewan-09** [comment]
Oauth will only work in production.

**Comment by RakeshSangem** [comment]
> Oauth will only work in production.

Oh, thanks for the confirmation👍

**Comment by leewan-09** [comment]
> > > ### Hey @leewan-09 , Why it's asking for username and password when click on continue with google?
> > > Screenshot 2022-09-21 143749
> > 
> > 
> > this will show in preview link and dev environment. for production it will show the actual provider auth
> 
> So can we merge this PR?

From my side it done

**Review by rohitdasu — APPROVED** [review]

**Pull request merged**
