### PR TITLE
Moving join us to footer

### LINKED ISSUE #326: [CHORE] put Join us links in footer
### Description

Having the links, where it's currently located, is taking too much space unnecessarily. It would be nice if it could be placed in footer.
image

### PR DESCRIPTION
**Pull request by jdomil**
### Fixes Issue

Closes #326 

### Changes proposed

Remove Join Us section from the main section of the landing page, and add it to the footer. Reduced the text size and margin to reduce the space it takes

### Note to reviewers

Hey! I'm new to the repo and a beginner developer, so please don't hesitate to leave as much feedback as you need. I am not entirely sure this is what you were looking for, so please let me know if I misunderstood the issue.

### Screenshots
Screenshot 2023-01-14 at 14 12 25

### CODE REVIEW

**Comment by rohitdasu** [comment]
hi @jdomil  please have a look at this build error, thanks

Screenshot 2023-01-14 at 7 18 25 PM

**Comment by rohitdasu** [comment]
also i think we should remove the join us text from the footer... and make the icons little bit smaller... what you think?

**Comment by jdomil** [comment]
Hey @rohitdasu! Yes, that's perfect, I wasn't too sure if you wanted to remove the Join Us text altogether. I made those changes and it looks like there aren't any build errors now. Happy to make any additional tweaks to the icons, just let me know.

**Review by rohitdasu — APPROVED** [review]
Looks good! thanks for the contribution.

**Pull request merged**
