### PR TITLE
hero section 

### PR DESCRIPTION
**Pull request by Yazdun**
### Changes proposed

I'm in the process of creating a landing page for the project. I re-created the hero section for now and I'd like to get some feedbacks

### CODE REVIEW

**Comment by RakeshSangem** [comment]
Hey @Yazdun,  In light mode, the `JOIN US` button doesn't look good. I'm talking about boosting the contrast of button background. What do you think @leewan-09  and @rohitdasu ?

button light mode

**Comment by rohitdasu** [comment]
> Hey @Yazdun, In light mode, the `JOIN US` button doesn't look good. I'm talking about boosting the contrast of button background. What do you think @leewan-09 and @rohitdasu ?
> 
> button light mode

yes, a little more contrast can make it better

**Comment by Yazdun** [comment]
> > Hey @Yazdun, In light mode, the `JOIN US` button doesn't look good. I'm talking about boosting the contrast of button background. What do you think @leewan-09 and @rohitdasu ?
> > button light mode
> 
> yes, a little more contrast can make it better

I increased the background color a little bit, but I think the current one looks cleaner, it has a flat style. what do you guys think?

image

**Comment by leewan-09** [comment]
Looks good

**Comment by rohitdasu** [comment]
IMO previous one was looking better because we already have darker text

**Comment by Yazdun** [comment]
> IMO previous one was looking better because we already have darker text

yeah I agree, I think it the lighter background looks better. and it's obvious that it's a CTA. so should we keep it this way or should we update it?

**Comment by rohitdasu** [comment]
> > IMO previous one was looking better because we already have darker text
> 
> yeah I agree, I think the lighter background looks better. and it's obvious that it's a CTA. so should we keep it this way or should we update it?

yeah let's keep it this way only. 👍

**Review by rohitdasu — APPROVED** [review]

**Review by leewan-09 — APPROVED** [review]
LGTM 👍🏾

**Pull request merged**
