### PR TITLE
Improve projects page accessibility

### LINKED ISSUE #241: [FEATURE] Improve projects page accessibility
### Description

The accessibility of the projects page could be improved by using the right tags.

Since it's a list of projects, `ul` should be used instead of `div`.  `li` also should be used instead of the inner `div`.

Screenshot (138)

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
### Fixes Issue
Closes #241 

### Changes proposed
 - I used the right semantics.

### Note to reviewers
I decided to use `ul` for the general container since there will always be at least one project.

### CODE REVIEW

**Comment by rohitdasu** [comment]
hi @Olaleye-Blessing could you please do the same thing to user/profile page? there also we are showing project list. thanks

**Comment by Olaleye-Blessing** [comment]
@rohitdasu Yea, it's been updated.

**Review by rohitdasu — APPROVED** [review]
LGTM

**Review by leewan-09 — APPROVED** [review]
LGTM 👍🏾

**Pull request merged**
