### PR TITLE
resolved projects cards issues

### LINKED ISSUE #154: [BUG] fix inconsistent sizes of the project card
## 1. Fix in consistent sizes of the project card
project card

## 2. Add border to project card and tech stack chips
light mode

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Yazdun**
### Fixes Issue

Closes #154

### Changes proposed

Fixed the mentioned issues

### Screenshots

issue

### CODE REVIEW

**Comment by rohitdasu** [comment]
@Yazdun i've a question, does it maintain the size of the card irrespective of description text ?

**Comment by rohitdasu** [comment]
also noticed that the gap between searchbar and project section is too much (mobile and desktop view). can we reduce it so that it would look good ?

Screenshot 2022-09-19 at 1 04 29 PM

**Comment by Yazdun** [comment]
> @Yazdun i've a question, does it maintain the size of the card irrespective of description text ?

no but once we have dynamic data, we can easily come up with a solution, like giving a fix height to desc. but we need some real data to try that

**Comment by Yazdun** [comment]
> also noticed that the gap between searchbar and project section is too much (mobile and desktop view). can we reduce it so that it would look good ?
> 
> Screenshot 2022-09-19 at 1 04 29 PM

yeah I've already removed the gap in the current PR, take a another look at the PR's screenshot, I think it's look better without the gap too

**Comment by rohitdasu** [comment]
> > also noticed that the gap between searchbar and project section is too much (mobile and desktop view). can we reduce it so that it would look good ?
> > Screenshot 2022-09-19 at 1 04 29 PM
> 
> yeah I've already removed the gap in the current PR, take a another look at the PR's screenshot, I think it's look better without the gap too

yup, it's looking great now

**Comment by rohitdasu** [comment]
> > @Yazdun i've a question, does it maintain the size of the card irrespective of description text ?
> 
> no but once we have dynamic data, we can easily come up with a solution, like giving a fix height to desc. but we need some real data to try that

okay, for now i've an easy small idea. can we just show 160 characters only for the description? and add 3 dots(...) at the end if there are more than 160 characters. what's your opinion on this?

**Comment by Yazdun** [comment]
> > > @Yazdun i've a question, does it maintain the size of the card irrespective of description text ?
> > 
> > 
> > no but once we have dynamic data, we can easily come up with a solution, like giving a fix height to desc. but we need some real data to try that
> 
> okay, for now i've an easy small idea. can we just show 160 characters only for the description? and add 3 dots(...) at the end if there are more than 160 characters. what's your opinion on this?

good idea, I'm on it

**Comment by Yazdun** [comment]
character limits are added now

**Review by rohitdasu — APPROVED** [review]

**Pull request merged**
