### PR TITLE
Feature/prisma

### PR DESCRIPTION
**Pull request by ykhokhaneshiya**
#105 

Remove ? and made fields mandatory

### CODE REVIEW

**Comment by AdityaPainuli** [comment]
hey @ykhokhaneshiya could you look over why is it showing merging conflicts

**Comment by ykhokhaneshiya** [comment]
@RakeshSangem , resolved it.

**Comment by AdityaPainuli** [comment]
It's not solving all the issues I mentioned in #105 but it's ok we can work on that right now I think we can merge this one. Thanks for the contribution @ykhokhaneshiya

**Comment by rohitdasu** [comment]
@AdityaPainuli if it's not solving the all issues of #105 then let's not close that issue. but we can merge this PR. what you say?

**Pull request merged**
