### PR TITLE
Navbar avatar and logout button

### LINKED ISSUE #163: [FEATURE] add user avatar-dropdown to the navbar
### Description

Requirements: 

(large view)
add avatar to the navbar when user is successfully logged in. on clicking on the avatar should open a dropdown. where we should have two options
- profile
- logout

(mobile view)
in mobile mode show the options in the sidemenu. take inspiration from below 👇  

IMG_2575

### PR DESCRIPTION
**Pull request by leewan-09**
### Fixes Issue #163 
closes #163 

### Changes proposed
- Topbar avatar and logout button
- Sidebar avatar and logout button 

### Screenshots

Screenshot 2022-09-24 at 12 54 27

localhost_3000_

### CODE REVIEW

**Comment by rohitdasu** [comment]
any reasons for replacing <main> tag with <div> tag? @leewan-09

**Comment by rohitdasu** [comment]
@leewan-09 is this PR ready for review? i am seeing you made it as a draft PR.

**Comment by RakeshSangem** [comment]
> @leewan-09 is this PR ready for review? i am seeing you made it as a draft PR.

I accidentally made this PR as ready. Sorry for that!

**Comment by leewan-09** [comment]
> any reasons for replacing main tag with div tag? @leewan-09 

SharedLayout have Main tag.

**Comment by leewan-09** [comment]
> @leewan-09 is this PR ready for review? i am seeing you made it as a draft PR.

There is bug. In mobile phone. Im not able to see signout button

**Comment by leewan-09** [comment]
Screenshot 2022-09-24 at 12 54 27

**Review by rohitdasu — APPROVED** [review]
LGTM, thanks 🙏

**Pull request merged**
