### PR TITLE
Fix: Replace 'any' and make strongly typed components

### LINKED ISSUE #178: [BUG] replace 'any' and make strongly typed components
### Description

In our app lot of placing we are using `any` type. that's not a good practice. we need help with that. anyone with good typescript experience can fix this. thanks 🙏 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by ctoffanin**
### Fixes Issue
Closes #178 

### Changes proposed
- Replace `any` with more suitable types in the `httpResponse.ts` file
- Replace `any` type of `coverImage` in `SubmitProject` component and make cover image optional

### CODE REVIEW

**Comment by rohitdasu** [comment]
@leewan-09 could you check it

**Review by leewan-09 — APPROVED** [review]
LGTM

**Comment by rohitdasu** [comment]
@leewan-09 did you check other files as well? is there other files left making strict typings

**Comment by leewan-09** [comment]
> @leewan-09 did you check other files as well? is there other files left making strict typings

I did check

**Comment by rohitdasu** [comment]
> > @leewan-09 did you check other files as well? is there other files left making strict typings
> 
> I did check

awesome

**Comment by rohitdasu** [comment]
@ctoffanin could you resolve the conflicts?

**Comment by ctoffanin** [comment]
> @ctoffanin could you resolve the conflicts?

Yes, done

**Review by rohitdasu — APPROVED** [review]
LGTM 👍

**Pull request merged**
