### PR TITLE
fixed login card UI

### LINKED ISSUE #153: [BUG] improve login card and fix theme issues
### Description

Login card UI can be improved
- Login card background not changing according to theme mode.
- Fix inconsistent spacing of the card items
- add border to the login card

### Screenshots

login UI

### PR DESCRIPTION
**Pull request by Rounak-28**
### Closes #153

### CODE REVIEW

**Comment by rohitdasu** [comment]
@RakeshSangem i think the button text should be at centre. but i don't think currently it's at the correct position (slightly on right side). what's your thought?

Screenshot 2022-09-18 at 3 37 07 PM

**Comment by Rounak-28** [comment]
fixing that

**Comment by rohitdasu** [comment]
thanks @Rounak-28

**Comment by Rounak-28** [comment]
please check

**Comment by rohitdasu** [comment]
@RakeshSangem

**Comment by RakeshSangem** [comment]
Hey @Rounak-28 , Could you fix padding issues. I mean follow some padding for login UI.

## Reference Image 
projectmate login


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Rounak-28** [comment]
sorry I don't understand

**Comment by RakeshSangem** [comment]
> sorry I don't understand


> sorry I don't understand

@rohitdasu Could you explain to Rounak.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

**Comment by rohitdasu** [comment]
> Hey @Rounak-28 , Could you fix padding issues. I mean follow some padding for login UI.
> 
> ## Reference Image
> projectmate login
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

@RakeshSangem could you please explain on which part the padding should be fixed? it would be helpful to understand.

**Comment by RakeshSangem** [comment]
Add border to card then it will great in my opinion.

**Comment by Rounak-28** [comment]
> Add border to card then it will great in my opinion.

Which color and how much width should I give to the border?

**Comment by RakeshSangem** [comment]
1 or 2px fine and don't use %100 black.

**Comment by Rounak-28** [comment]
@RakeshSangem please check how's this looking

**Comment by rohitdasu** [comment]
@Rounak-28 could you add color #eeeeee as border color please?

**Comment by Rounak-28** [comment]
`#eeeeee` border does not looks good in light mode

**Comment by rohitdasu** [comment]
@Rounak-28 i don't like the orange color for border for sure. use some lighter black color please.

**Comment by Rounak-28** [comment]
how about white border on dark mode and something like gray for light mode?

**Comment by rohitdasu** [comment]
> how about white border on dark mode and something like gray for light mode?

white is fine but that shouldn't be 100% white. lighter is better

**Comment by RakeshSangem** [comment]
I suggest colors for you. `#4e4e4e` and `#959595` Choose according with themes

**Comment by rohitdasu** [comment]
also check how the colors should change for both light and dark mode. we are using next-themes. see how we can set these values @Rounak-28

**Comment by Rounak-28** [comment]
@rohitdasu @RakeshSangem check now

**Review by RakeshSangem — APPROVED** [review]
Looking good to me🎉

**Review by rohitdasu — APPROVED** [review]

**Pull request merged**
