### PR TITLE
Add project details page

### LINKED ISSUE #134: [FEATURE] Create Project's detail page [FE]
### Description

Create projects details page.

- Detail page contains more info of the project
- User will navigate to `project details page` when he/she clicks on contribute button

### PR DESCRIPTION
**Pull request by JakubChorzepa**
### Fixes Issue

Closes #134

### CODE REVIEW

**Review by rohitdasu — APPROVED** [review]
LGTM 🎉

**Review by leewan-09 — CHANGES_REQUESTED** [review]
image

Could you fix this overflow? 
This could help you: https://tailwindcss.com/docs/word-break

**Comment by JakubChorzepa** [comment]
> image
> 
> Could you fix this overflow? This could help you: https://tailwindcss.com/docs/word-break

Fine I already added word break

**Review by leewan-09 — APPROVED** [review]
LGTM 👍🏾

**Pull request merged**
