### PR TITLE
Add Project-Page

### LINKED ISSUE #94: [FEATURE] add project form
### Description

The `add project` form should open when user clicks on the `add project` button which is present in the fab action button.

### PR DESCRIPTION
**Pull request by AdityaPainuli**
Closes #94

### CODE REVIEW

**Comment by rohitdasu** [comment]
@AdityaPainuli i think @RakeshSangem is working on new design of add project page. the current design has alignment issues. Please wait till the design is ready.

**Comment by AdityaPainuli** [comment]
Got it 👍

**Comment by RakeshSangem** [comment]
## @AdityaPainuli Browse files container border border not visible in the light mode. Could you fix that?

Screenshot 2022-09-23 202042

**Comment by AdityaPainuli** [comment]
Yes thanks for the suggestion will take a look into it 👍

**Comment by RakeshSangem** [comment]
> Yes thanks for the suggestion will take a look into it 👍

Awesome👍

**Review by RakeshSangem — CHANGES_REQUESTED** [review]
@AdityaPainuli  Could you fix the button width same as input fields! What do you think @rohitdasu ?

## Reference image
button size

**Comment by rohitdasu** [comment]
> @AdityaPainuli Could you fix the button width same as input fields! What do you think @rohitdasu ?
> 
> ## Reference image
> button size

thanks @RakeshSangem for pointing this. @AdityaPainuli please follow the design.

**Comment by rohitdasu** [comment]
also the `note text` below dropdown should be left aligned.

**Comment by RakeshSangem** [comment]
refer
button size


> also the `note text` below dropdown should be left aligned.

thanks rohit, I missed that one:(

**Comment by AdityaPainuli** [comment]
> @AdityaPainuli Could you fix the button width same as input fields! What do you think @rohitdasu ?
> 
> ## Reference image
> button size

For the submit button, should I go with our advice of making it the same width as the input fields or with the Figma design?

**Comment by rohitdasu** [comment]
> > @AdityaPainuli Could you fix the button width same as input fields! What do you think @rohitdasu ?
> > ## Reference image
> > button size
> 
> For the submit button, should I go with your advice of making it the same width as the input fields or with the Figma design?

Figma 🙌

**Comment by RakeshSangem** [comment]
> > @AdityaPainuli Could you fix the button width same as input fields! What do you think @rohitdasu ?
> > ## Reference image
> > button size
> 
> For the submit button, should I go with your advice of making it the same width as the input fields or with the Figma design?

I would say, Just fix the issue only. It's looking good with the same size as input fields.

**Comment by rohitdasu** [comment]
> > > @AdityaPainuli Could you fix the button width same as input fields! What do you think @rohitdasu ?
> > > ## Reference image
> > > button size
> > 
> > 
> > For the submit button, should I go with your advice of making it the same width as the input fields or with the Figma design?
> 
> I would say, Just fix the issue only. It's looking good with the same size as input fields.

it's not good idea for larger screens imo. we can do this for smaller screens but not for larger ones.

**Comment by AdityaPainuli** [comment]
> an do this for smaller screens but not fo

you are saying right let's go with Figma design.

**Comment by leewan-09** [comment]
Add Project page should take the full width 
Screenshot 2022-09-23 at 23 31 23

This is how it should be 
Screenshot 2022-09-23 at 23 31 34

**Pull request closed without merging**
