### PR TITLE
feat: added tooltip to nav icons

### LINKED ISSUE #104: [FEATURE] add tooltip for socials and dark/light mode icon.
## Description

- User might occasionally be unfamiliar with the icon user for.
- In these situations, having a tooltip for social icons and icons in dark/light modes will be helpful.
- So, add `Tooltip` for socials and dark/light mode theme icon.

## For reference:
Screenshot 2022-09-08 234847

### PR DESCRIPTION
**Pull request by rohitdasu**
### Fixes Issue

fixes #104 

### Changes proposed

* added tooltip for navbar icons 
* added link to logo

### Screenshots

Screenshot 2022-09-10 at 9 57 55 AM

### CODE REVIEW

**Comment by RakeshSangem** [comment]
Awesome 👍

**Comment by rohitdasu** [comment]
> Awesome 👍

could you please approve the PR @RakeshSangem 😁

**Comment by RakeshSangem** [comment]
> > Awesome 👍
> 
> could you please approve the PR @RakeshSangem 😁

In my opinion we can reduce the font size. What do you say?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by rohitdasu** [comment]
yeah sure, what size should work? @RakeshSangem

**Comment by RakeshSangem** [comment]
> yeah sure, what size should work? @RakeshSangem

`text-lg` or `text-xl` works fine ig.

**Comment by AdityaPainuli** [comment]
I think we should remove the tooltip on a mobile screen as it is giving something like this  -
image

**Comment by RakeshSangem** [comment]
> I think we should remove the tooltip on a mobile screen as it is giving something like this - image

Yup, @rohitdasu could you fix it?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by rohitdasu** [comment]
> > yeah sure, what size should work? @RakeshSangem
> 
> `text-lg` or `text-xl` works fine ig. @rohitdasu
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

text lg is way bigger than what we have currently. i've text-sm looks good

**Review by RakeshSangem — APPROVED** [review]
LGTM⚡

**Pull request merged**
