### PR TITLE
Fixed line break in project component

### PR DESCRIPTION
**Pull request by KidesLeo**
### Fixes Issue #231 
Text overflow on project component title.

### Changes proposed
Added truncate class on title header.

### CODE REVIEW

**Comment by leewan-09** [comment]
Could you fill in the details @KidesLeo. At least fill these:

`Fixes Issue
Changes proposed`

**Comment by KidesLeo** [comment]
> Could you fill in the details @KidesLeo. At least fill these:
> 
> `Fixes Issue` `Changes proposed`

My apologies, updated my request.

**Review by leewan-09 — APPROVED** [review]

**Review by RakeshSangem — APPROVED** [review]

**Comment by RakeshSangem** [comment]
> can we display "..." at the end?

Yes, we can with the help of this `text-ellipsis` class

**Comment by rohitdasu** [comment]
> > can we display "..." at the end?
> 
> Yes, we can do that with the help of this `text-ellipsis` class

@KidesLeo could you please work on this

**Comment by KidesLeo** [comment]
> > > can we display "..." at the end?
> > 
> > 
> > Yes, we can do that with the help of this `text-ellipsis` class
> 
> @KidesLeo could you please work on this

So it wasn't adding the "..." due to [this interesting property of flex](https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size). I've updated it by giving the header a minimum width of 0. Problem fixed, sorry for the delay!
image

**Review by rohitdasu — APPROVED** [review]
LGTM

**Review by Yazdun — APPROVED** [review]

**Pull request merged**
