### PR TITLE
chore: remove unnecessary icons import (#405)

### LINKED ISSUE #405: [CHORE] Remove unnecessary icons import
### Description

In footer and sidebar components there are unnecessary imports of icons like this:
`import * as SiIcon from 'react-icons/si';`

We'd like to remove those imports and replace them with only icons that are used in these components.

### PR DESCRIPTION
**Pull request by pewpewnor**
### Fixes Issue

Closes #405 

### Changes proposed

Changes in directory:
1. /components/LandingPage/Footer

To only import the necessary icons.

### Note to reviewers

This PR  right now only consists of refactoring the imports for the footer in the landing page, later on, a commit can be added to this PR to refactor the sidebar component as well.

### Screenshots

### CODE REVIEW

**Review by JakubChorzepa — COMMENTED** [review]
Hey, everything looks good for me, I think you can do this solution in sidebar too.

**Comment by pewpewnor** [comment]
Alright @JakubChorzepa, I finished implementing the solution on the sidebar.

**Comment by pewpewnor** [comment]
I think its ready to go

**Review by JakubChorzepa — APPROVED** [review]

**Review by rohitdasu — APPROVED** [review]
LGTM

**Pull request merged**
