### PR TITLE
Update README.md

### LINKED ISSUE #365: [DOCS] improve readme file
### Description

Make it more user friendly and try to match the colors with our current color scheme(theme) of application.

use ChatGPT if need 😁

### PR DESCRIPTION
**Pull request by abhrajitray77**
### Fixes Issue
[DOCS] improve readme file #365

closes #365 

### Changes proposed

-Aligned Header to center
-Added Landing page pic
-Changed Color scheme according to site.
-Added Emojis for key highlights

### Screenshots
Screenshot from 2023-04-05 21-44-16
Screenshot from 2023-04-05 21-44-25
Screenshot from 2023-04-05 21-44-30
Screenshot from 2023-04-05 21-44-42

### CODE REVIEW

**Comment by rohitdasu** [comment]
Screenshot 2023-04-05 at 9 51 10 PM

could you left align this button?

**Comment by abhrajitray77** [comment]
Screenshot from 2023-04-05 22-00-27

Done

**Comment by rohitdasu** [comment]
> Screenshot from 2023-04-05 22-00-27
> 
> Done

please make the title also left align. with left aligned button title isn't looking good.

**Comment by abhrajitray77** [comment]
True

**Comment by abhrajitray77** [comment]
Screenshot from 2023-04-05 22-03-42

done

**Review by rohitdasu — APPROVED** [review]
Looks good to me

**Pull request merged**
