### PR TITLE
Add prisma seed command

### PR DESCRIPTION
**Pull request by JakubChorzepa**

### CODE REVIEW

**Comment by rohitdasu** [comment]
@JakubChorzepa could you please add instructions to the commands in readme.md file?
we don't have anything related to prisma in instruction section so it would be nice if you can add all commands related to it. thanks 😊

**Comment by JakubChorzepa** [comment]
Yeah I can but someone who knows it should check it if I understand and type it properly.

**Comment by rohitdasu** [comment]
> Yeah I can but someone who knows it should check it if I understand and type it properly.

yeah sure, @leewan-09 can review it 👍

**Comment by JakubChorzepa** [comment]
You can have a look on these changes

**Comment by rohitdasu** [comment]
this looks good to me. but waiting for others opinion on this.

**Review by leewan-09 — APPROVED** [review]
LGTM 👍

**Comment by leewan-09** [comment]
Btw, @JakubChorzepa  did you test it?

**Comment by JakubChorzepa** [comment]
Yeah I used that commands

**Comment by JakubChorzepa** [comment]
I dropped my collections and once again used the commands and they are working correctly.
PrismaPush
PrismaSeed

**Review by rohitdasu — APPROVED** [review]
LGTM

**Pull request merged**
